//! Matrix regression tests covering multiple years, time indices, genders, and edge cases.
//! Test data is generated by the JS iztro library and compared against rs-iztro output.

use rs_iztro::data::types::*;
use rs_iztro::i18n::{
    translate_earthly_branch, translate_five_elements_class, translate_palace, translate_star,
};
use rs_iztro::by_solar;
use serde_json::Value;

static MATRIX_DATA: &str = include_str!("matrix_results.json");

fn parse_gender(s: &str) -> Gender {
    match s {
        "男" => Gender::Male,
        "女" => Gender::Female,
        _ => panic!("Unknown gender: {}", s),
    }
}

#[test]
fn test_matrix_regression() {
    let cases: Vec<Value> = serde_json::from_str(MATRIX_DATA).expect("Failed to parse matrix_results.json");

    let mut failures: Vec<String> = Vec::new();
    let lang = Language::ZhCN;

    for (i, case) in cases.iter().enumerate() {
        let params = &case["params"];
        let solar_date = params["solar_date"].as_str().unwrap();
        let time_index = params["time_index"].as_u64().unwrap() as u8;
        let gender_str = params["gender"].as_str().unwrap();
        let gender = parse_gender(gender_str);

        let astrolabe = by_solar(solar_date, time_index, gender, true, lang, Algorithm::Default);

        let context = format!(
            "case[{}]: solar_date={}, time_index={}, gender={}",
            i, solar_date, time_index, gender_str
        );

        // Soul palace earthly branch
        let expected_soul_branch = case["soul_palace_branch"].as_str().unwrap();
        let actual_soul_branch = translate_earthly_branch(astrolabe.earthly_branch_of_soul_palace, lang);
        if actual_soul_branch != expected_soul_branch {
            failures.push(format!(
                "{}: soul_palace_branch expected '{}', got '{}'",
                context, expected_soul_branch, actual_soul_branch
            ));
        }

        // Body palace earthly branch
        let expected_body_branch = case["body_palace_branch"].as_str().unwrap();
        let actual_body_branch = translate_earthly_branch(astrolabe.earthly_branch_of_body_palace, lang);
        if actual_body_branch != expected_body_branch {
            failures.push(format!(
                "{}: body_palace_branch expected '{}', got '{}'",
                context, expected_body_branch, actual_body_branch
            ));
        }

        // Five elements class
        let expected_fec = case["five_elements_class"].as_str().unwrap();
        let actual_fec = translate_five_elements_class(astrolabe.five_elements_class, lang);
        if actual_fec != expected_fec {
            failures.push(format!(
                "{}: five_elements_class expected '{}', got '{}'",
                context, expected_fec, actual_fec
            ));
        }

        // Palace[0] name
        let expected_p0_name = case["palace_0_name"].as_str().unwrap();
        let actual_p0_name = translate_palace(astrolabe.palaces[0].name, lang);
        if actual_p0_name != expected_p0_name {
            failures.push(format!(
                "{}: palace_0_name expected '{}', got '{}'",
                context, expected_p0_name, actual_p0_name
            ));
        }

        // Palace[0] major stars count
        let expected_p0_major = case["palace_0_major_count"].as_u64().unwrap() as usize;
        let actual_p0_major = astrolabe.palaces[0].major_stars.len();
        if actual_p0_major != expected_p0_major {
            failures.push(format!(
                "{}: palace_0_major_count expected {}, got {}",
                context, expected_p0_major, actual_p0_major
            ));
        }

        // Soul star
        let expected_soul_star = case["soul_star"].as_str().unwrap();
        let actual_soul_star = translate_star(astrolabe.soul, lang);
        if actual_soul_star != expected_soul_star {
            failures.push(format!(
                "{}: soul_star expected '{}', got '{}'",
                context, expected_soul_star, actual_soul_star
            ));
        }

        // Body star
        let expected_body_star = case["body_star"].as_str().unwrap();
        let actual_body_star = translate_star(astrolabe.body, lang);
        if actual_body_star != expected_body_star {
            failures.push(format!(
                "{}: body_star expected '{}', got '{}'",
                context, expected_body_star, actual_body_star
            ));
        }
    }

    if !failures.is_empty() {
        panic!(
            "\n{} matrix test failures out of {} cases:\n{}",
            failures.len(),
            cases.len(),
            failures.join("\n")
        );
    }

    println!("All {} matrix test cases passed.", cases.len());
}
